import type { Article } from '../types';

export const ARTICLES: Article[] = [
  {
    id: 'art1', slug: 'progressive-overload-guide', title: 'The Complete Guide to Progressive Overload',
    excerpt: 'Learn the #1 principle behind consistent muscle and strength gains. Without progressive overload, your body has no reason to adapt.',
    content: `## What Is Progressive Overload?\n\nProgressive overload is the gradual increase of stress placed upon the body during exercise training. It's the foundational principle behind all strength and hypertrophy programs.\n\n## Why It Matters\n\nYour body adapts to the demands you place on it. If you always lift the same weight for the same reps, your body has no reason to grow stronger or build more muscle. You must progressively increase the challenge.\n\n## How to Apply It\n\n### 1. Add More Weight\nThe most straightforward method. Add 2.5-5 lbs to the bar when you can complete all prescribed reps with good form.\n\n### 2. Add More Reps\nIf you can't add weight yet, aim for more reps within your target range (e.g., go from 3×8 to 3×10 before adding weight).\n\n### 3. Add More Sets\nIncrease total training volume by adding an extra set to key exercises.\n\n### 4. Decrease Rest Time\nPerforming the same work in less time is also a form of progressive overload.\n\n### 5. Improve Form\nBetter technique with the same weight means more muscle activation and effective load.\n\n## Common Mistakes\n\n- **Too much too fast** — Increasing weight before form is solid\n- **Ignoring recovery** — Progression requires adequate sleep, nutrition, and rest days\n- **Program hopping** — Switching programs every week prevents you from tracking progress\n\nStay consistent, track your lifts, and trust the process.`,
    coverImage: 'https://images.pexels.com/photos/3888405/pexels-photo-3888405.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', publishedAt: '2024-11-15', category: 'Training',
  },
  {
    id: 'art2', slug: 'protein-intake-guide', title: 'How Much Protein Do You Really Need?',
    excerpt: 'Cut through the noise: evidence-based protein recommendations for muscle building, fat loss, and general health.',
    content: `## The Science of Protein Intake\n\nProtein is the most important macronutrient for body composition. Here's what the research actually says.\n\n## General Recommendations\n\n- **Sedentary adults**: 0.8g per kg of body weight\n- **Active individuals**: 1.2-1.6g per kg\n- **Muscle building**: 1.6-2.2g per kg\n- **Fat loss (while preserving muscle)**: 2.0-2.4g per kg\n\n## Timing Matters (A Little)\n\nThe "anabolic window" isn't as narrow as once thought, but distributing protein across 3-5 meals per day does optimize muscle protein synthesis.\n\n### Optimal Per-Meal Protein\n\nAim for 25-40g of protein per meal to maximally stimulate muscle protein synthesis.\n\n## Best Protein Sources\n\n### Animal Sources\n- Chicken breast (31g per 100g)\n- Eggs (13g per 100g)\n- Greek yogurt (10g per 100g)\n- Salmon (25g per 100g)\n- Lean beef (26g per 100g)\n\n### Plant Sources\n- Lentils (9g per 100g cooked)\n- Tofu (8g per 100g)\n- Chickpeas (9g per 100g)\n- Quinoa (4g per 100g cooked)\n\n## Key Takeaway\n\nFor most gym-goers, aim for **1.6-2.2g of protein per kg of body weight per day**, spread across multiple meals.`,
    coverImage: 'https://images.pexels.com/photos/6388452/pexels-photo-6388452.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', publishedAt: '2024-11-20', category: 'Nutrition',
  },
  {
    id: 'art3', slug: 'sleep-and-muscle-growth', title: '5 Ways Sleep Affects Your Muscle Growth',
    excerpt: 'You can\'t out-train bad sleep. Here\'s exactly how sleep quality impacts your gains and recovery.',
    content: `## Sleep: The Most Underrated Anabolic\n\nYou can have the perfect training program and diet, but without adequate sleep, you're leaving significant gains on the table.\n\n## 1. Growth Hormone Release\n\nUp to 75% of human growth hormone (HGH) is released during deep sleep. HGH is critical for muscle repair, fat metabolism, and recovery.\n\n## 2. Protein Synthesis\n\nMuscle protein synthesis peaks during sleep. Poor sleep reduces protein synthesis by up to 18%.\n\n## 3. Testosterone Production\n\nStudies show that sleeping only 5 hours per night can reduce testosterone levels by 10-15%.\n\n## 4. Cortisol Regulation\n\nSleep deprivation increases cortisol, a catabolic hormone that breaks down muscle tissue and promotes fat storage.\n\n## 5. Training Performance\n\nPoor sleep reduces strength output, endurance capacity, motivation, and coordination.\n\n## How to Optimize Sleep for Gains\n\n1. **Aim for 7-9 hours** per night\n2. **Consistent schedule** — same bed/wake time daily\n3. **Cool, dark room** — 65-68°F (18-20°C)\n4. **No screens** 30-60 minutes before bed\n5. **Avoid caffeine** after 2 PM\n\n## The Bottom Line\n\nSleep is when your body actually builds muscle. Prioritize it like you prioritize your training.`,
    coverImage: 'https://images.pexels.com/photos/3838705/pexels-photo-3838705.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', publishedAt: '2024-12-01', category: 'Recovery',
  },
  {
    id: 'art4', slug: 'deload-week-guide', title: 'When and How to Deload',
    excerpt: 'Strategic deload weeks prevent burnout and plateaus. Learn the signs you need one and how to structure it.',
    content: `## What Is a Deload?\n\nA deload is a planned reduction in training stress — usually volume, intensity, or both — to let your body recover while staying in the gym habit.\n\n## Signs You Need a Deload\n\n- Persistent joint aches that warm-ups do not fix\n- Strength regressing for 2+ weeks despite adequate sleep and nutrition\n- Motivation crash and unusually poor sleep quality\n- Elevated resting heart rate for several days\n\n## How to Deload\n\n### Option 1: Reduce Volume\nKeep the same weights but cut sets in half for one week.\n\n### Option 2: Reduce Intensity\nUse 60-70% of your working weights while keeping movement patterns the same.\n\n### Option 3: Active Recovery\nSwap heavy compounds for lighter technique work, mobility, and easy cardio.\n\n## How Often?\n\nMost intermediate lifters benefit from a deload every 4-8 weeks. Advanced athletes running high volume may deload more often.\n\n## The Bottom Line\n\nDeloads are not laziness — they are part of long-term progression.`,
    coverImage: 'https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', publishedAt: '2025-01-10', category: 'Training',
  },
  {
    id: 'art5', slug: 'hydration-performance', title: 'Hydration for Training Performance',
    excerpt: 'Even mild dehydration hurts strength, endurance, and focus. Here is a practical hydration framework for lifters.',
    content: `## Why Hydration Matters\n\nWater supports blood volume, joint lubrication, temperature regulation, and nutrient transport. Losing just 2% of body weight in fluids can reduce performance.\n\n## Daily Baseline\n\nA practical starting point is **30-40 ml per kg of body weight** per day, plus extra for training and hot climates.\n\n## Around Workouts\n\n- Drink 400-600 ml in the 2 hours before training\n- Sip during sessions longer than 60 minutes\n- Replace roughly 150% of sweat losses after training (weigh yourself before/after once to estimate)\n\n## Electrolytes\n\nSweaty sessions may need sodium and potassium — especially in heat or during long cardio. Whole foods plus a pinch of salt in meals often suffices for most lifters.\n\n## Practical Tips\n\n- Keep a bottle visible at your desk\n- Use urine color as a rough guide (pale yellow is ideal)\n- Do not wait until you feel thirsty in hot weather\n\n## Key Takeaway\n\nHydration is a daily habit, not something to fix only on training days.`,
    coverImage: 'https://images.pexels.com/photos/416471/pexels-photo-416471.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', publishedAt: '2025-01-18', category: 'Nutrition',
  },
  {
    id: 'art6', slug: 'warm-up-fundamentals', title: 'The Smart Warm-Up for Strength Training',
    excerpt: 'A good warm-up raises temperature, prepares joints, and rehearses the lifts you are about to train — without wasting energy.',
    content: `## Goals of a Warm-Up\n\n1. Increase core temperature\n2. Mobilize the joints you will load\n3. Practice movement patterns with submaximal loads\n\n## Sample 10-Minute Lower Body Warm-Up\n\n- 3 minutes easy bike or brisk walk\n- Leg swings and hip circles\n- Bodyweight squats and glute bridges\n- 2 ramp-up sets on your first lift\n\n## Sample Upper Body Warm-Up\n\n- Band pull-aparts and shoulder dislocates\n- Push-ups or incline push-ups\n- Empty-bar or light-dumbbell sets of your first press or row\n\n## Common Mistakes\n\n- **Too much static stretching before heavy lifting** — save long holds for after training\n- **Skipping warm-up sets** — ramp sets improve groove and reduce injury risk\n- **Fatiguing cardio** — keep it easy; the workout is the hard part\n\n## Key Takeaway\n\nWarm up specifically for what you are training that day. Ten focused minutes beats thirty random minutes.`,
    coverImage: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', publishedAt: '2025-02-02', category: 'Training',
  },
];
