export const VOCAB_FA = {
  muscleGroups: {
    Chest: 'سینه',
    Triceps: 'پشت بازو',
    Shoulders: 'شانه‌ها',
    Quadriceps: 'چهارسر ران',
    Glutes: 'باسن',
    Hamstrings: 'همسترینگ',
    Back: 'پشت',
    Biceps: 'جلو بازو',
    'Rear Delts': 'دلت پشتی',
    Core: 'میان‌تنه',
    Legs: 'پاها',
    Calves: 'ساق پا',
  },
  equipment: {
    Barbell: 'هالتر',
    Bench: 'نیمکت',
    'Squat Rack': 'جایگاه اسکوات',
    'Pull-Up Bar': 'میله بارفیکس',
    Dumbbells: 'دمبل',
    'Leg Press Machine': 'دستگاه پرس پا',
    None: 'بدون تجهیزات',
    Treadmill: 'تردمیل',
    'Cable Machine': 'دستگاه سیم‌کش',
    'Calf Machine': 'دستگاه ساق پا',
  },
  difficulty: {
    beginner: 'مبتدی',
    intermediate: 'متوسط',
    advanced: 'پیشرفته',
  },
  exerciseType: {
    strength: 'قدرتی',
    cardio: 'هوازی',
    corrective: 'اصلاحی',
    mobility: 'تحرک',
  },
  programLevel: {
    Beginner: 'مبتدی',
    Intermediate: 'متوسط',
    Advanced: 'پیشرفته',
  },
  categories: {
    Training: 'تمرین',
    Nutrition: 'تغذیه',
    Recovery: 'بازیابی',
  },
};
