import type { Exercise } from '../types';

export const EXERCISES: Exercise[] = [
  { id: 'ex1', slug: 'barbell-bench-press', name: 'Barbell Bench Press', instructions: 'Lie on a flat bench, grip the barbell slightly wider than shoulder width. Lower the bar to your mid-chest, keeping elbows at about 45 degrees. Press back up to full arm extension. Keep your feet flat on the floor and maintain a slight arch in your lower back.', commonMistakes: 'Bouncing the bar off your chest. Flaring elbows too wide. Lifting hips off the bench. Not using a full range of motion.', difficulty: 'intermediate', type: 'strength', muscleGroups: ['Chest', 'Triceps', 'Shoulders'], equipment: ['Barbell', 'Bench'] },
  { id: 'ex2', slug: 'barbell-squat', name: 'Barbell Back Squat', instructions: 'Place the barbell on your upper traps. Stand with feet shoulder-width apart, toes slightly out. Descend by pushing hips back and bending knees simultaneously. Go as low as mobility allows (at least parallel). Drive back up through your heels.', commonMistakes: 'Knees caving inward. Rounding lower back. Not hitting proper depth. Shifting weight to toes.', difficulty: 'intermediate', type: 'strength', muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'], equipment: ['Barbell', 'Squat Rack'] },
  { id: 'ex3', slug: 'deadlift', name: 'Conventional Deadlift', instructions: 'Stand with feet hip-width apart, bar over mid-foot. Hinge at hips to grip the bar just outside your knees. Brace your core, keep chest up, and drive through the floor. Lock out at the top with hips and knees extended. Lower in a controlled manner.', commonMistakes: 'Rounding the back. Starting with hips too high or too low. Not bracing core. Hyperextending at lockout.', difficulty: 'advanced', type: 'strength', muscleGroups: ['Back', 'Glutes', 'Hamstrings'], equipment: ['Barbell'] },
  { id: 'ex4', slug: 'overhead-press', name: 'Overhead Press', instructions: 'Stand with feet shoulder-width apart. Hold barbell at shoulder height, palms forward. Press the bar directly overhead. Lock out arms at the top. Lower back to shoulders with control.', commonMistakes: 'Excessive back lean. Not fully locking out. Using legs to assist (unless doing push press).', difficulty: 'intermediate', type: 'strength', muscleGroups: ['Shoulders', 'Triceps'], equipment: ['Barbell'] },
  { id: 'ex5', slug: 'pull-up', name: 'Pull-Up', instructions: 'Hang from a bar with palms facing away, slightly wider than shoulder width. Pull yourself up until your chin is over the bar. Lower with control to full arm extension. Keep your core engaged throughout.', commonMistakes: 'Kipping or swinging. Not going to full extension at bottom. Not getting chin over bar.', difficulty: 'intermediate', type: 'strength', muscleGroups: ['Back', 'Biceps'], equipment: ['Pull-Up Bar'] },
  { id: 'ex6', slug: 'barbell-row', name: 'Barbell Bent-Over Row', instructions: 'Hinge at hips with slight knee bend, back at ~45 degrees. Grip barbell with hands shoulder-width apart. Pull the bar to your lower chest/upper abdomen. Squeeze shoulder blades at the top. Lower with control.', commonMistakes: 'Using momentum. Not maintaining hip hinge. Pulling to the wrong position.', difficulty: 'intermediate', type: 'strength', muscleGroups: ['Back', 'Biceps', 'Rear Delts'], equipment: ['Barbell'] },
  { id: 'ex7', slug: 'dumbbell-lateral-raise', name: 'Dumbbell Lateral Raise', instructions: 'Stand with dumbbells at your sides. Raise arms out to the sides until parallel with the floor. Keep a slight bend in elbows. Lower with control. Lead with elbows, not hands.', commonMistakes: 'Using too heavy a weight. Swinging the weights. Shrugging shoulders up.', difficulty: 'beginner', type: 'strength', muscleGroups: ['Shoulders'], equipment: ['Dumbbells'] },
  { id: 'ex8', slug: 'leg-press', name: 'Leg Press', instructions: 'Sit in the leg press machine with feet shoulder-width apart on the platform. Lower the weight by bending knees to about 90 degrees. Push back to start without locking knees completely.', commonMistakes: 'Locking knees at the top. Placing feet too high or low. Letting knees cave in. Rounding lower back.', difficulty: 'beginner', type: 'strength', muscleGroups: ['Quadriceps', 'Glutes'], equipment: ['Leg Press Machine'] },
  { id: 'ex9', slug: 'plank', name: 'Plank', instructions: 'Support your body on forearms and toes, forming a straight line from head to heels. Engage your core and hold. Keep hips level — do not let them sag or pike up. Breathe steadily.', commonMistakes: 'Sagging hips. Piking hips too high. Holding breath. Looking up instead of down.', difficulty: 'beginner', type: 'strength', muscleGroups: ['Core', 'Shoulders'], equipment: ['None'] },
  { id: 'ex10', slug: 'running-treadmill', name: 'Treadmill Running', instructions: 'Start at a comfortable pace. Maintain upright posture with slight forward lean. Land on midfoot, not heels. Keep arms at 90 degrees. Gradually increase speed as desired.', commonMistakes: 'Overstriding. Holding onto handrails. Looking down at feet. Starting too fast.', difficulty: 'beginner', type: 'cardio', muscleGroups: ['Legs', 'Core'], equipment: ['Treadmill'] },
  { id: 'ex11', slug: 'incline-dumbbell-press', name: 'Incline Dumbbell Press', instructions: 'Set an incline bench to 30–45 degrees. Press dumbbells from chest level to full extension above your upper chest. Keep wrists stacked over elbows and lower with control.', commonMistakes: 'Setting the bench too steep. Bouncing weights at the bottom. Flaring elbows excessively.', difficulty: 'intermediate', type: 'strength', muscleGroups: ['Chest', 'Shoulders', 'Triceps'], equipment: ['Dumbbells', 'Bench'] },
  { id: 'ex12', slug: 'romanian-deadlift', name: 'Romanian Deadlift', instructions: 'Hold a barbell at hip height with a shoulder-width grip. Push hips back while keeping a soft knee bend and flat back. Lower until you feel a strong hamstring stretch, then drive hips forward to stand.', commonMistakes: 'Rounding the lower back. Bending knees too much like a squat. Not hinging at the hips.', difficulty: 'intermediate', type: 'strength', muscleGroups: ['Hamstrings', 'Glutes', 'Back'], equipment: ['Barbell'] },
  { id: 'ex13', slug: 'lat-pulldown', name: 'Lat Pulldown', instructions: 'Grip the bar slightly wider than shoulder width. Pull the bar to your upper chest while squeezing your shoulder blades together. Control the weight on the way up without shrugging.', commonMistakes: 'Leaning too far back. Pulling behind the neck. Using momentum from the hips.', difficulty: 'beginner', type: 'strength', muscleGroups: ['Back', 'Biceps'], equipment: ['Cable Machine'] },
  { id: 'ex14', slug: 'barbell-curl', name: 'Barbell Curl', instructions: 'Stand tall with an underhand grip on the barbell. Curl the bar toward your shoulders while keeping elbows pinned to your sides. Lower slowly to full extension.', commonMistakes: 'Swinging the torso. Moving elbows forward. Using too much weight.', difficulty: 'beginner', type: 'strength', muscleGroups: ['Biceps'], equipment: ['Barbell'] },
  { id: 'ex15', slug: 'tricep-rope-pushdown', name: 'Tricep Rope Pushdown', instructions: 'Attach a rope to a high cable pulley. Keep elbows at your sides and extend your arms downward until fully locked out. Spread the rope slightly at the bottom, then return with control.', commonMistakes: 'Letting elbows drift forward. Leaning over the cable. Partial range of motion.', difficulty: 'beginner', type: 'strength', muscleGroups: ['Triceps'], equipment: ['Cable Machine'] },
  { id: 'ex16', slug: 'standing-calf-raise', name: 'Standing Calf Raise', instructions: 'Stand on the edge of a step or calf machine platform with balls of feet on the surface. Rise onto your toes as high as possible, pause briefly, then lower heels below the platform for a stretch.', commonMistakes: 'Bouncing at the bottom. Bending knees excessively. Using too little range of motion.', difficulty: 'beginner', type: 'strength', muscleGroups: ['Calves'], equipment: ['Calf Machine'] },
  { id: 'ex17', slug: 'face-pull', name: 'Face Pull', instructions: 'Set a rope attachment at upper-chest height. Pull toward your face with elbows high and external rotation at the shoulders. Squeeze rear delts and upper back at the end range.', commonMistakes: 'Pulling too low toward the chest. Using excessive weight. Not externally rotating at the finish.', difficulty: 'beginner', type: 'corrective', muscleGroups: ['Rear Delts', 'Back'], equipment: ['Cable Machine'] },
  { id: 'ex18', slug: 'walking-lunge', name: 'Walking Lunge', instructions: 'Step forward into a lunge until both knees are near 90 degrees. Keep your front knee over your mid-foot and torso upright. Push through the front heel to step into the next lunge.', commonMistakes: 'Short steps that let the knee pass the toes. Leaning forward. Letting the back knee slam the floor.', difficulty: 'beginner', type: 'strength', muscleGroups: ['Quadriceps', 'Glutes', 'Hamstrings'], equipment: ['Dumbbells'] },
  { id: 'ex19', slug: 'cable-chest-fly', name: 'Cable Chest Fly', instructions: 'Set cables at shoulder height with a slight forward lean. Bring handles together in a wide arc with a soft elbow bend. Squeeze your chest at the center, then return with control.', commonMistakes: 'Turning the movement into a press. Overstretching at the start. Shrugging shoulders.', difficulty: 'intermediate', type: 'strength', muscleGroups: ['Chest'], equipment: ['Cable Machine'] },
  { id: 'ex20', slug: 'barbell-hip-thrust', name: 'Barbell Hip Thrust', instructions: 'Rest your upper back on a bench with a padded barbell across your hips. Drive through your heels to lift your hips until your torso is parallel to the floor. Squeeze glutes at the top and lower under control.', commonMistakes: 'Hyperextending the lower back. Pushing through toes instead of heels. Not pausing at lockout.', difficulty: 'intermediate', type: 'strength', muscleGroups: ['Glutes', 'Hamstrings'], equipment: ['Barbell', 'Bench'] },
];
